Patch to fix bug caused by new importlib-metadata package.
importlib-metadata upgrade to version 5.0.0 from 4.13.0 resulting in a `AttributeError: 'EntryPoints' object has no attribute 'items'`. 
Reverting the package fixes this bug and allows us to use the openstack client cli commands again.